# 连接池配置
spring:
  application:
    name: partnet-backend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/yupao
      username: root
      password: hsp
      driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400 #设置session失效时间
    store-type: redis #表示从 redis 读写 session,默认是 none，表示存储在单台服务器
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  #Redis 连接信息配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 0

# mybatis-plus的配置
# 已经自动开启驼峰映射
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #手动关闭驼峰映射
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #添加日志
  type-aliases-package: com.yzj.partnetBackend.model
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      #table-prefix: news_ # 设置表的前缀
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值

server:
  port: 8081
  servlet:
    context-path: /api #指定接口全局api
    session:
      cookie:
        #后端设置cookie允许在哪个域名下可携带
        domain: localhost #注意，这里只规定了localhost域名下可携带cookie，127.0.0.1都不行！！！
        #所以前端访问时请访问localhost域名

# springdoc-openapi项目配置
# springdoc-openapi项目访问访问地址: http://127.0.0.1:8081/api/doc.html
springdoc:
  swagger-ui:
    # path: 配置swagger-ui.html/UI界面的访问路径,默认为/swagger-ui.html
    path: /swagger-ui.html
    # tags-sorter: 接口文档中的tags排序规则,默认为alpha,可选值为alpha(按字母顺序排序)或as-is(按照在代码中定义的顺序排序)
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    # path: 配置api-docs的访问路径,默认为/v3/api-docs
    path: /v3/api-docs
  group-configs:
      # group-configs: 配置分组信息
    - group: 'default'
      # paths-to-match: 配置要匹配的路径,默认为/**
      paths-to-match: '/**'
      # packages-to-scan: 配置要扫描的包的路径,直接配置为Controller类所在的包名即可
      packages-to-scan: com.yzj.partnetBackend.controller

# knife4j的增强配置，不需要增强可以不配
# knife4j项目访问访问地址:http://127.0.0.1:8080/api/doc.html#/home
#knife4j:
#  enable: true    # 开启knife4j,无需添加@EnableKnife4j注解
#  setting:
#    language: zh_cn   #中文
#    swagger-model-name: 实体列表   #默认为: Swagger Models
#  basic: # 开启Swagger的Basic认证功能,默认是false
#    enable: true
#    username: admin
#    password: 123456

